version: '3.8'

services:
  verification-service:
    build: .
    container_name: tar-verification-service
    ports:
      - "8082:8082"
    environment:
      - BLOCKCHAIN_RPC_URL=${BLOCKCHAIN_RPC_URL:-http://host.docker.internal:8545}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS:-0x5FbDB2315678afecb367f032d93F642f64180aa3}
      - NETWORK_ID=${NETWORK_ID:-31337}
      - METADATA_SERVICE_URL=${METADATA_SERVICE_URL:-http://host.docker.internal:8081}
      - SERVER_PORT=8082
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./logs:/app/logs"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/verify/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tar-network

networks:
  tar-network:
    driver: bridge
